version: '2'

services:

    ansible_control_00:
        image: ansible_control_host
        volumes:
            - ./ansible:/root/ansible
            - ./bin:/usr/local/bin:ro
            - ./storage/host_00:/var/deploy
        ports:
            - "8500:8500"
        networks:
            - code-network

    ansible_managed_01:
        image: ansible_managed_host
        volumes:
            - ./bin:/usr/local/bin:ro
            - ./storage/host_01:/var/deploy
        networks:
            - code-network

    ansible_managed_02:
        image: ansible_managed_host
        volumes:
            - ./bin:/usr/local/bin:ro
            - ./storage/host_02:/var/deploy
        networks:
            - code-network

    ansible_managed_03:
        image: ansible_managed_host
        volumes:
            - ./bin:/usr/local/bin:ro
            - ./storage/host_03:/var/deploy
        networks:
            - code-network

    ansible_managed_04:
        image: ansible_managed_host
        volumes:
            - ./bin:/usr/local/bin:ro
            - ./storage/host_04:/var/deploy
        networks:
            - code-network

networks:
    code-network:
        driver: bridge